### ISSUE TITLE
Native TYPO3 categories

### ISSUE THREAD

**Issue by cweiske** [lochmueller/faq#18]
It would be nice if the FAQ would use TYPO3's native categories instead of adding its own category record type.

**Comment by lochmueller** [comment]
Hey @cweiske ,
thanks for the idea. Do you have time for a pull request?
Regards,
Tim

**Comment by cweiske** [comment]
No. We've moved on to building an own extension.

**Comment by lochmueller** [comment]
OK. then i will close this issue for now. Thanks for the quick response ;)
