### ISSUE TITLE
Exception when clicking vote buttons

### ISSUE THREAD

**Issue by cweiske** [lochmueller/faq#19]
When clicking on the "helpful" button in the frontend, I get an exception:

> #1365429656: TYPO3 Fatal Error: Extension key "hdnet_faq" is NOT loaded!

URL loaded is:

http://localhost:5607/page/?question=1&mode=1&id=120&type=7076&fluid-widget-id=6f541e4bfa996efb529058742d679902&action=vote

**Comment by lochmueller** [comment]
Fixed a few seconds ago with this patch: https://github.com/lochmueller/faq/commit/7b15e24603c379491308f3784cfb6f7f88cc7226
