### ISSUE TITLE
Error on form submit when selecting a category in the dropdown

### ISSUE THREAD

**Issue by djangones** [lochmueller/faq#20]
faq: 2.10
autoloader: 5.0.3
Typo3: 8.7.17

If the form is sent, an error message appears, because the cHash parameter in the form is probably not passed correctly? The link (with CHash) to access all categories works as expected.

Page not found
The page did not exist or was inaccessible. Reason: Request parameters could not be validated (&amp;cHash empty)

**Comment by djangones** [comment]
It looks like there is no cHash passed with the form or automatically generated with the form helper.
Adding `arguments="{dummy: 1}"` in the fluid form helper seems to be a workaround.

**Comment by lochmueller** [comment]
Strange workarround... but if this fix the problem, feel free to add a pull request...

**Comment by lochmueller** [comment]
No more feedback related to this issue. I will close this issue...
Perhaps the current version (TYPO3 and FAQ) will already solve this problem.
