### ISSUE TITLE
ext_tables.sql

### ISSUE THREAD

**Issue by GuillaumeG22** [lochmueller/faq#3]
Hello,

There are no ext_tables.sql file. This file contains the SQL structure. 

Is it normal?

**Comment by sirdiego** [comment]
Hi @GuillaumeG22, yes it is! We use the handy SmartObjects feature of the autoloader extension. See here: https://docs.typo3.org/typo3cms/extensions/autoloader/1.9.2/Loader/SmartObjects.html and here: http://typo3.org/extensions/repository/view/autoloader

**Comment by lochmueller** [comment]
Thanks @sirdiego .... I will close this issue.

**Comment by GuillaumeG22** [comment]
I use TYPO3 7.3.

autoloader or faq is'nt work on TYPO3 7.3 for creating sql tables ?

**Comment by lochmueller** [comment]
Hey @GuillaumeG22 

TYPO3 7.3 is no supported version. But EXT:autoloader and also EXT:faq should work with 7.3 too. Please install both extension and run a database compare in the install tool. Further more it is recommended to change to a support TYPO3 version (7.5).

Regards,
Tim

**Comment by GuillaumeG22** [comment]
I just tried on TYPO3 7.5.

It's good for creating sql tables.

Thank you ! 

Regards,
Guillaume
