### ISSUE TITLE
not resolved dependency

### ISSUE THREAD

**Issue by carlossmedina** [lochmueller/faq#32]
unresolved dependency on Typo3 9.5

Using version ^3.0 for lochmueller/faq
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing lochmueller/faq (3.0.0): Downloading (100%)
Writing lock file
Generating autoload files
Generating class alias map file
Inserting class alias loader into main autoload.php file
> typo3cms install:fixfolderstructure
The following directory structure has been fixed:
> typo3cms install:generatepackagestates

  [ UnexpectedValueException ]
  The package "faq" depends on "autoloader" which is not present in the syste
  m.

install:generatepackagestates [--framework-extensions FRAMEWORK-EXTENSIONS] [--excluded-extensions EXCLUDED-EXTENSIONS] [--activate-default]

Script typo3cms install:generatepackagestates handling the typo3-cms-scripts event returned with error code 255
Script @typo3-cms-scripts was called via post-autoload-dump

**Comment by lochmueller** [comment]
Hey @carlossmedina 
thanks for the note. I add the missing dependency to the autoloader package in the composer.json file.
Regards,
Tim
