### ISSUE TITLE
Undeclared arguments passed to ViewHelper

### ISSUE THREAD

**Issue by lisardo2** [lochmueller/faq#34]
TYPO3 9.5.x
faq 3.0.0
Standard-Templates

Results in this error message: 

    Undeclared arguments passed to ViewHelper HDNET\Faq\ViewHelpers\Widget\VoteViewHelper: question, counters. Valid arguments are: customWidgetId

**Comment by lochmueller** [comment]
Hey @lisardo2 
Thanks for the reporting. Fiexed in current master: https://github.com/lochmueller/faq/commit/7bb483a81fb1e75bde559c6bb8aa7b578863ea5a
Regards,
Tim
