### ISSUE TITLE
ERROR faq.php Line 73

### ISSUE THREAD

**Issue by sebastiangaertner** [lochmueller/faq#35]
I have installed the autoloader and the faq. Included the typoscript in an ext template.  but i get this in the frontend. 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: trim() expects parameter 1 to be string, null given | TypeError thrown in file /html/typo3/typo3conf/ext/faq/Classes/Domain/Model/Request/Faq.php in line 73. Requested URL: https://greenstand.org/faq

**Comment by lochmueller** [comment]
Thanks for the info. Current patch in master solve this problem....

**Comment by sebastiangaertner** [comment]
Thank you!
