### ISSUE TITLE
Issue with setup faq / autoloader

### ISSUE THREAD

**Issue by rengert** [lochmueller/faq#38]
I installed faq and autoloader via composer. 
Not the typo3 instance is not running anymore:

request="" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'HDNET\Autoloader\Loader' not found | Error thrown in file /Users/.../web/typo3conf/ext/autoloader/ext_localconf.php in line 12.

The class itself is available and fine. Any ideas?

**Comment by lochmueller** [comment]
Both extensions are installed in TYPO3?

**Comment by rengert** [comment]
Thanks for the quick response. Well typo3 is not working anymore i only have access to the install tool. There is see only the autoloader configuration.

**Comment by rengert** [comment]
I disabled autoloader (and faq) in install tool, and it is working again ... but well without faq extension i wanted to install.

**Comment by lochmueller** [comment]
Hmm... looks strange. If you install autoloader first and then faq?
The class exists... perhaps some problems with the composer autoloader mechanims in your project?

Regards,
Tim

**Comment by rengert** [comment]
I guess you are right, i have the same issue if i only install autoload.

**Comment by lochmueller** [comment]
Could you check your vendor/composer dir related to autoload information? I cannot rebuild this error/situation on my dev server...

**Comment by rengert** [comment]
Thanks for the hint, i was able to reproduce the issue on multiple systems. But now know what is missing, so i was able to resolve this manually. Not the best solution, i know. But now it is clear it has nothing to do with your extension. 

After updating the files everything is working as expected. I still have no idea why for some packages composer mapping files are updated and for some not.

I tried with some other random extensions and was able to reproduce similar issues. The issues were not so heavy, but i guess it depends on where the newly introduced namespaces are used.

Sorry but thanks for your time.
