### ISSUE TITLE
manual sorting

### ISSUE THREAD

**Issue by toccamonium-fe** [lochmueller/faq#41]
Hi,
In my case I need manual sorting hence I used the selection mode and selected faq datasets. But on webpage, I just get message "no faqs found". Did I something wrong?

![grafik](https://user-images.githubusercontent.com/55410878/77339412-02bab300-6d2c-11ea-8ed5-5d98a25e245e.png)

**Comment by lochmueller** [comment]
Hey @toccamonium-fe ,
thanks for the ticket. There are fixes in the current master for manual sorting. I don't know when I release this changes. The lines for getting the questions looks right: https://github.com/lochmueller/faq/blob/master/Classes/Controller/FaqController.php#L77
Feel free to send some more tecnical information or debugging stuff.
Regards,
Tim
