### ISSUE TITLE
Version 3.0.1 not loading the page

### ISSUE THREAD

**Issue by sebastiangaertner** [lochmueller/faq#42]
When
config.concatenateJs = 0
is set in the setup of the template,  the Page does not load anymore.

**Comment by lochmueller** [comment]
Note: The faq.js require jQuery in front of the JS. I added a note in the TS.
If the JS is not the problem, I need more information.
Perhaps you could disable the JS load of EXT:faq via `page.includeJSFooter.faq  >`
