### ISSUE TITLE
$_EXTKEY not available in TYPO3 9.5 Configuration/TCA/Overrides

### ISSUE THREAD

**Issue by mat-hew1** [lochmueller/faq#43]
Usage of empty $_EXTKEY in Configuration/TCA/Overrides/pages.php leads to unexpected results in TCE, where all pages that have no module selected seem to contain FAQ. The reason is that the value for FAQ is empty at that point.
Please use different config files for different TYPO3 versions or explicite naming.

**Comment by lochmueller** [comment]
Thanks for the hint. Fixed in current master.
