### ISSUE TITLE
User questions "FAQ Eingabe" are not submitted

### ISSUE THREAD

**Issue by griebie** [lochmueller/faq#5]
TYPO3 7.6.4
tx_faq v1.0.1
sr_freecap v2.3.1
autoloader v1.11.4

Hi,

see above my local configuration with which a user question (module "FAQ Eingabe") in the EXT tx_faq won't be sent or prepared as a data record in the sys folder.

Thanks for hints in advance, 
Regards
Thorsten

**Comment by lochmueller** [comment]
Hey @griebie ,
no feedback/pull request. So I will drop this issue.
I will recheck the FAQ extension in my next community sprint.
Regards,
Tim
