### ISSUE TITLE
TYPO3 10 Support?

### ISSUE THREAD

**Issue by maximaexchen** [lochmueller/faq#53]
Question:
There seems no Version 4 for TYPO3 10 Download?

**Comment by maximaexchen** [comment]
Ok. My fault. Found it under Tags.
But on the typo3 site the version support for TYPO3 10 is not listet.

**Comment by lochmueller** [comment]
Hey @maximaexchen 
The TER push was broken (I suggest using composer), so there are no TER releases in this time.
Fixed with the last release. I will close this issue.

Regards,
Tim
