### ISSUE TITLE
Search / Filter not working - Faq::getCategory() must be an instance of QuestionCategory

### ISSUE THREAD

**Issue by Chrisswald** [lochmueller/faq#54]
I always get this error, when I don't activate "Hide search" option: 
Return value of HDNET\Faq\Domain\Model\Request\Faq::getCategory() must be an instance of HDNET\Faq\Domain\Model\QuestionCategory, null returned

- TYPO3 10.4.32
- faq 4.1.1
- autoloader 7.3.6

Any ideas?

**Comment by lochmueller** [comment]
Please select a category in the FAQ entry. But you are right... this sould be optinal.

**Comment by Chrisswald** [comment]
What do you mean with faq entry? The Question? I got one selected there.

![image](https://user-images.githubusercontent.com/38914601/216645265-b990f2f4-e363-4f00-baf0-fac3f6cc6fdd.png)

**Comment by lochmueller** [comment]
You are right... I will check this in the next days/weeks....

**Comment by Chrisswald** [comment]
Maybe this? https://github.com/lochmueller/faq/pull/51/commits/3dfcaa1feeb01988054d84d3fd83525a1b706eca

**Comment by lochmueller** [comment]
Hey @Chrisswald 
You are right. Do you try the current release or the patch?
Regards,
Tim

**Comment by Chrisswald** [comment]
I am now using the current release with TYPO3 11

**Comment by lochmueller** [comment]
Great. I also add this https://github.com/lochmueller/faq/commit/71d087ea2f9bae6bab742bba5d5570fac10e9dc3 and close the issue now.
