### ISSUE TITLE
Separate FAQ use in multi-domain

### ISSUE THREAD

**Issue by griebie** [lochmueller/faq#6]
Hi,

I've got a multi-domain installation in which I want to use a faq plugin on each domain. Is there I setting I can do to separate their categories? Right now I can choose the categories from domain A also in the faq entries within domain B.

Thanks for any hint,
Regards
Griebie

**Comment by lochmueller** [comment]
Hey @griebie 
puhh ;) I don't know. This is a general problem of system categories in TYPO3 and I think there are same PageTSConfig settings to set the root node of the category selection. But I do not know the syntaax at the moment...

I will check this in the next days...

Regards,
Tim

**Comment by jousch** [comment]
@lochmueller Is there some similar functionality in ext:news?

**Comment by lochmueller** [comment]
https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Select/Index.html#treeconfig
`rootUid (integer, optional) : uid of the record that shall be considered as the root node of the tree. In general this might be set by Page TSconfig`

Do you try this one....

**Comment by lochmueller** [comment]
I close this issue, because the reduction of the category tree is part of the core configuration. Take a look at https://github.com/lochmueller/faq/issues/6#issuecomment-226305241
